spring:
  datasource:
    url: jdbc:mysql://192.168.194.128:3306/TESTDB
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  address: localhost
  port: 8080

#启用shutdown （方便linux下关闭）
# 关闭请求 默认 （发送post请求）
# 如果提示connection refused  可能是因为 端口或者ip不对
endpoints:
  shutdown:
    enabled: true
    sensitive: false
    #配置自定的路径前后缀 curl -X POST localhost:8080/shutdown
    #配置自定的路径前后缀 curl -X POST localhost:8080/shutdown
management:
  context-path: /manage